
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

plugin.selection=pkgServices.pkgMicrokernel.clsMultipleChoiceQuestion
plugin.multimedia=pkgServices.pkgMicrokernel.clsMultimediaQuestion
plugin.case=pkgServices.pkgMicrokernel.clsCaseQuestion

