/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgUI;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import pkgDomain.clsController;
import pkgServices.clsInterfaceBridge;

/**
 *
 * @author Acer3
 */
public class uiLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(uiLogin.class.getName());
    private final uiRegisterUser attUiRegisterUser = new uiRegisterUser();
    
    /**
     * Creates new form uiLogin
     */
    public uiLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogin = new javax.swing.JPanel();
        cmdCloseApp = new javax.swing.JButton();
        cmdLogin = new javax.swing.JButton();
        cmdRegisterUser = new javax.swing.JButton();
        attIcon = new javax.swing.JLabel();
        jpInternal = new javax.swing.JPanel();
        jlNickName = new javax.swing.JLabel();
        jftNickName = new javax.swing.JTextField();
        jlPassword = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new Dimension(400, 600));

        jpLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        cmdCloseApp.setBackground(new java.awt.Color(204, 204, 204));
        cmdCloseApp.setText("Close");
        cmdCloseApp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCloseApp.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdCloseApp.addActionListener(this::cmdCloseAppActionPerformed);

        cmdLogin.setBackground(new java.awt.Color(204, 204, 204));
        cmdLogin.setText("Login");
        cmdLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdLogin.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdLogin.addActionListener(this::cmdLoginActionPerformed);

        cmdRegisterUser.setBackground(new java.awt.Color(204, 204, 204));
        cmdRegisterUser.setText("Register");
        cmdRegisterUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdRegisterUser.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdRegisterUser.addActionListener(this::cmdRegisterUserActionPerformed);

        attIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgSources/account_circle_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz241.png"))); // NOI18N

        jpInternal.setBackground(new java.awt.Color(255, 255, 255));
        jpInternal.setForeground(new java.awt.Color(255, 255, 255));

        jlNickName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlNickName.setText("Nick name");
        jlNickName.setPreferredSize(new java.awt.Dimension(100, 40));

        jftNickName.setBackground(new java.awt.Color(204, 204, 204));
        jftNickName.setMinimumSize(new java.awt.Dimension(100, 40));
        jftNickName.setPreferredSize(new java.awt.Dimension(100, 40));

        jlPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlPassword.setText("Password");
        jlPassword.setPreferredSize(new java.awt.Dimension(100, 40));

        jpfPassword.setBackground(new java.awt.Color(204, 204, 204));
        jpfPassword.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jpInternalLayout = new javax.swing.GroupLayout(jpInternal);
        jpInternal.setLayout(jpInternalLayout);
        jpInternalLayout.setHorizontalGroup(
            jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jftNickName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInternalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInternalLayout.setVerticalGroup(
            jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jftNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(attIcon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                .addComponent(attIcon)
                .addGap(18, 18, 18)
                .addComponent(jpInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jpLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdCloseAppActionPerformed

    private void cmdRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterUserActionPerformed
        attUiRegisterUser.setVisible(true);
        attUiRegisterUser.opSetUiLogin(this);
        attUiRegisterUser.opLoadComboBox(clsController.opGetInstance().opGetMyRoles());
        this.setVisible(false);
    }//GEN-LAST:event_cmdRegisterUserActionPerformed

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        String varObj = new String(jpfPassword.getPassword());
        if (clsInterfaceBridge.opValidateLogin(jftNickName.getText(), varObj)) {       
            if (clsInterfaceBridge.opValidateLogin(jftNickName.getText(), varObj)) {
                JOptionPane.showMessageDialog(null, "Ingreso Exitoso", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo ingresar", "Advertecia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor verifique los datos", "Advertecia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmdLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new uiLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attIcon;
    private javax.swing.JButton cmdCloseApp;
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdRegisterUser;
    private javax.swing.JTextField jftNickName;
    private javax.swing.JLabel jlNickName;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JPanel jpInternal;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPasswordField jpfPassword;
    // End of variables declaration//GEN-END:variables
}
