/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgUI;

import pkgDomain.clsQuestion;

/**
 *
 * @author santi
 */
public class uiQuestion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(uiQuestion.class.getName());
    private clsQuestion attQuestion = new clsQuestion();
    /**
     * Creates new form uiQuestion
     */
    public uiQuestion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void opUpdateQuestion(clsQuestion prmQuestion) {
        attQuestion= prmQuestion;
    }
    public void opLoadUI (){
        jtfQuestionId.setText(attQuestion.opGetOUID());
        jtfQuestionName.setText(attQuestion.opGetName());
        jtfQuestionTxt.setText(attQuestion.opGetDescription());
        jtfQuestionOptionA.setText(attQuestion.opGetOptionA());
        jtfQuestionOptionB.setText(attQuestion.opGetOptionB());
        jtfQuestionOptionC.setText(attQuestion.opGetOptionC());
        jtfQuestionOptionD.setText(attQuestion.opGetOptionD());
        jtfQuestionRightAnswer.setText(attQuestion.opGetRightAnswer());
        jtfQuestionState.setText(attQuestion.opGetState());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Lbl3 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        Lbl5 = new javax.swing.JLabel();
        Lbl6 = new javax.swing.JLabel();
        Lbl7 = new javax.swing.JLabel();
        jcbQuestionState = new javax.swing.JComboBox<>();
        cmdQuestionUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfQuestionId = new javax.swing.JTextField();
        jtfQuestionName = new javax.swing.JTextField();
        jtfQuestionTxt = new javax.swing.JTextField();
        jtfQuestionOptionA = new javax.swing.JTextField();
        jtfQuestionRightAnswer = new javax.swing.JTextField();
        jtfQuestionState = new javax.swing.JTextField();
        jtfQuestionOptionB = new javax.swing.JTextField();
        jtfQuestionOptionC = new javax.swing.JTextField();
        jtfQuestionOptionD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lbl8 = new javax.swing.JLabel();
        Lbl9 = new javax.swing.JLabel();
        Lbl10 = new javax.swing.JLabel();
        cmdCloseApp = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Question"));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 800));

        Lbl3.setText("Question:");

        Lbl4.setText("Option A:");

        Lbl5.setText("Right Answer:");

        Lbl6.setText("State:");

        Lbl7.setText("New State:");

        jcbQuestionState.setBackground(new java.awt.Color(204, 204, 204));
        jcbQuestionState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbQuestionState.addActionListener(this::jcbQuestionStateActionPerformed);

        cmdQuestionUpdate.setBackground(new java.awt.Color(204, 204, 204));
        cmdQuestionUpdate.setText("Update State");
        cmdQuestionUpdate.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdQuestionUpdate.addActionListener(this::cmdQuestionUpdateActionPerformed);

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jtfQuestionId.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionName.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionTxt.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionOptionA.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionRightAnswer.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionState.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionOptionB.setBackground(new java.awt.Color(204, 204, 204));
        jtfQuestionOptionB.addActionListener(this::jtfQuestionOptionBActionPerformed);

        jtfQuestionOptionC.setBackground(new java.awt.Color(204, 204, 204));

        jtfQuestionOptionD.setBackground(new java.awt.Color(204, 204, 204));
        jtfQuestionOptionD.addActionListener(this::jtfQuestionOptionDActionPerformed);

        Lbl8.setText("Option B:");

        Lbl9.setText("Option C:");

        Lbl10.setText("Option D:");

        cmdCloseApp.setBackground(new java.awt.Color(204, 204, 204));
        cmdCloseApp.setText("Close");
        cmdCloseApp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCloseApp.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdCloseApp.addActionListener(this::cmdCloseAppActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lbl10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(Lbl3)
                                        .addComponent(Lbl4)
                                        .addComponent(Lbl8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(Lbl9))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl6)
                                    .addComponent(Lbl5)
                                    .addComponent(Lbl7))))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfQuestionOptionD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfQuestionOptionC, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfQuestionState, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jcbQuestionState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfQuestionOptionA, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfQuestionName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfQuestionRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfQuestionId, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jtfQuestionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jtfQuestionOptionB, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cmdQuestionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfQuestionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfQuestionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl3)
                    .addComponent(jtfQuestionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl4)
                    .addComponent(jtfQuestionOptionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl8)
                    .addComponent(jtfQuestionOptionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfQuestionOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfQuestionOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Lbl5)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfQuestionRightAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfQuestionState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbQuestionState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl7))))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdQuestionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdQuestionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuestionUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdQuestionUpdateActionPerformed

    private void jcbQuestionStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuestionStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbQuestionStateActionPerformed

    private void jtfQuestionOptionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuestionOptionBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQuestionOptionBActionPerformed

    private void cmdCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdCloseAppActionPerformed

    private void jtfQuestionOptionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuestionOptionDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQuestionOptionDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new uiQuestion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl10;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel Lbl5;
    private javax.swing.JLabel Lbl6;
    private javax.swing.JLabel Lbl7;
    private javax.swing.JLabel Lbl8;
    private javax.swing.JLabel Lbl9;
    private javax.swing.JButton cmdCloseApp;
    private javax.swing.JButton cmdQuestionUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcbQuestionState;
    private javax.swing.JTextField jtfQuestionId;
    private javax.swing.JTextField jtfQuestionName;
    private javax.swing.JTextField jtfQuestionOptionA;
    private javax.swing.JTextField jtfQuestionOptionB;
    private javax.swing.JTextField jtfQuestionOptionC;
    private javax.swing.JTextField jtfQuestionOptionD;
    private javax.swing.JTextField jtfQuestionRightAnswer;
    private javax.swing.JTextField jtfQuestionState;
    private javax.swing.JTextField jtfQuestionTxt;
    // End of variables declaration//GEN-END:variables
}
