/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgUI;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import pkgDomain.clsRole;
import pkgServices.clsInterfaceBridge;
/**
 *
 * @author Acer3
 */
public class uiRegisterUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(uiRegisterUser.class.getName());
    private uiLogin attUiLogin;
    
    /**
     * Creates new form uiRegisterUser
     */
    public uiRegisterUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                // No hace nada al ganar el foco
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {
                // Al hacer clic fuera, se destruye la ventana al instante sin errores
                attUiLogin.setVisible(true);
                setVisible(false);
            }
        });
    }
    
    public void opSetUiLogin (uiLogin prmLogin){
        attUiLogin = prmLogin;
    }
    
    public void opLoadComboBox(List<clsRole> prmList) {
        jcbUserRole.removeAllItems(); // Limpia los elementos previos
        if (prmList != null) {
            for (clsRole varObj : prmList) {
                jcbUserRole.addItem(varObj.opGetName());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRegisterUser = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jpInternal = new javax.swing.JPanel();
        jlUserName = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jlUserNickName = new javax.swing.JLabel();
        jtfUserNickName = new javax.swing.JTextField();
        jlUserRole = new javax.swing.JLabel();
        jlUserPassword = new javax.swing.JLabel();
        jtfUserPassword = new javax.swing.JTextField();
        jcbUserRole = new javax.swing.JComboBox<>();
        cmdCloseApp = new javax.swing.JButton();
        cmdRegisterUser = new javax.swing.JButton();
        cmdBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new Dimension(400, 600));

        jpRegisterUser.setBackground(new java.awt.Color(255, 255, 255));
        jpRegisterUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Register User"));
        jpRegisterUser.setPreferredSize(new java.awt.Dimension(400, 600));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgSources/app_registration_200dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        jpInternal.setBackground(new java.awt.Color(255, 255, 255));

        jlUserName.setBackground(new java.awt.Color(255, 255, 255));
        jlUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUserName.setText("Name");

        jtfUserName.setBackground(new java.awt.Color(204, 204, 204));
        jtfUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlUserNickName.setBackground(new java.awt.Color(255, 255, 255));
        jlUserNickName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUserNickName.setText("Nick Name");

        jtfUserNickName.setBackground(new java.awt.Color(204, 204, 204));
        jtfUserNickName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlUserRole.setBackground(new java.awt.Color(255, 255, 255));
        jlUserRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUserRole.setText("Role");

        jlUserPassword.setBackground(new java.awt.Color(255, 255, 255));
        jlUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUserPassword.setText("Password");

        jtfUserPassword.setBackground(new java.awt.Color(204, 204, 204));
        jtfUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcbUserRole.setBackground(new java.awt.Color(204, 204, 204));
        jcbUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpInternalLayout = new javax.swing.GroupLayout(jpInternal);
        jpInternal.setLayout(jpInternalLayout);
        jpInternalLayout.setHorizontalGroup(
            jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInternalLayout.createSequentialGroup()
                        .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUserRole)
                            .addComponent(jlUserPassword))
                        .addGap(32, 32, 32)
                        .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jcbUserRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpInternalLayout.createSequentialGroup()
                        .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUserNickName)
                            .addComponent(jlUserName))
                        .addGap(24, 24, 24)
                        .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUserNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpInternalLayout.setVerticalGroup(
            jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInternalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUserName)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUserNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUserNickName))
                .addGap(23, 23, 23)
                .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUserRole)
                    .addComponent(jcbUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUserPassword))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cmdCloseApp.setBackground(new java.awt.Color(204, 204, 204));
        cmdCloseApp.setText("Close");
        cmdCloseApp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCloseApp.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdCloseApp.addActionListener(this::cmdCloseAppActionPerformed);

        cmdRegisterUser.setBackground(new java.awt.Color(204, 204, 204));
        cmdRegisterUser.setText("Register");
        cmdRegisterUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdRegisterUser.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdRegisterUser.addActionListener(this::cmdRegisterUserActionPerformed);

        cmdBack.setBackground(new java.awt.Color(204, 204, 204));
        cmdBack.setText("Back");
        cmdBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdBack.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdBack.addActionListener(this::cmdBackActionPerformed);

        javax.swing.GroupLayout jpRegisterUserLayout = new javax.swing.GroupLayout(jpRegisterUser);
        jpRegisterUser.setLayout(jpRegisterUserLayout);
        jpRegisterUserLayout.setHorizontalGroup(
            jpRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterUserLayout.createSequentialGroup()
                .addGroup(jpRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegisterUserLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegisterUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpRegisterUserLayout.createSequentialGroup()
                                .addComponent(cmdBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(cmdRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpRegisterUserLayout.setVerticalGroup(
            jpRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jpInternal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jpRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jpRegisterUser, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdCloseAppActionPerformed

    private void cmdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackActionPerformed
        attUiLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdBackActionPerformed

    private void cmdRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterUserActionPerformed
        if ( clsInterfaceBridge.opValidateRegister(jtfUserName.getText(), jtfUserNickName.getText(), jtfUserPassword.getText())) {
            if (clsInterfaceBridge.opRegisterUser(jtfUserName.getText(), jtfUserNickName.getText(), jcbUserRole.getSelectedItem().toString(), jtfUserPassword.getText())) {
                JOptionPane.showMessageDialog(null, "Registro Exitoso", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar", "Advertecia", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor verifique los datos", "Advertecia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmdRegisterUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new uiRegisterUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdCloseApp;
    private javax.swing.JButton cmdRegisterUser;
    private javax.swing.JLabel icon;
    private javax.swing.JComboBox<String> jcbUserRole;
    private javax.swing.JLabel jlUserName;
    private javax.swing.JLabel jlUserNickName;
    private javax.swing.JLabel jlUserPassword;
    private javax.swing.JLabel jlUserRole;
    private javax.swing.JPanel jpInternal;
    private javax.swing.JPanel jpRegisterUser;
    private javax.swing.JTextField jtfUserName;
    private javax.swing.JTextField jtfUserNickName;
    private javax.swing.JTextField jtfUserPassword;
    // End of variables declaration//GEN-END:variables
}
