/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgUI;

import java.util.List;
import javax.swing.JOptionPane;
import pkgDomain.clsControllerDomain;
import pkgDomain.clsQuestion;

/**
 *
 * @author santi
 */
public class uiSelectQuestion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(uiSelectQuestion.class.getName());
    private final uiQuestion attQuestion = new uiQuestion();
    /**
     * Creates new form uiSelectQuestion
     */
    public uiSelectQuestion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void opLoadComboBox(List<clsQuestion> prmList) {
        jcbSelectQuestion.removeAllItems(); // Limpia los elementos previos
        if (prmList != null) {
            for (clsQuestion varObj : prmList) {
                jcbSelectQuestion.addItem(varObj.opGetName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSelectQuestion = new javax.swing.JPanel();
        jcbSelectQuestion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdLoadQuestion = new javax.swing.JButton();
        cmdCloseApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("uiSelectQuestion");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jpSelectQuestion.setBackground(new java.awt.Color(255, 255, 255));
        jpSelectQuestion.setPreferredSize(new java.awt.Dimension(480, 500));

        jcbSelectQuestion.setBackground(new java.awt.Color(204, 204, 204));
        jcbSelectQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSelectQuestion.setPreferredSize(new java.awt.Dimension(72, 40));
        jcbSelectQuestion.addActionListener(this::jcbSelectQuestionActionPerformed);

        jLabel1.setText("Question");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Select a Question:");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgSystem/pkgSources/search_70dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        cmdLoadQuestion.setBackground(new java.awt.Color(204, 204, 204));
        cmdLoadQuestion.setText("Load Question");
        cmdLoadQuestion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdLoadQuestion.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdLoadQuestion.addActionListener(this::cmdLoadQuestionActionPerformed);

        cmdCloseApp.setBackground(new java.awt.Color(204, 204, 204));
        cmdCloseApp.setText("Close");
        cmdCloseApp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCloseApp.setPreferredSize(new java.awt.Dimension(100, 40));
        cmdCloseApp.addActionListener(this::cmdCloseAppActionPerformed);

        javax.swing.GroupLayout jpSelectQuestionLayout = new javax.swing.GroupLayout(jpSelectQuestion);
        jpSelectQuestion.setLayout(jpSelectQuestionLayout);
        jpSelectQuestionLayout.setHorizontalGroup(
            jpSelectQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectQuestionLayout.createSequentialGroup()
                .addGroup(jpSelectQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSelectQuestionLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbSelectQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSelectQuestionLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSelectQuestionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jpSelectQuestionLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(cmdLoadQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jpSelectQuestionLayout.setVerticalGroup(
            jpSelectQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectQuestionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpSelectQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSelectQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jpSelectQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdLoadQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jpSelectQuestion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSelectQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSelectQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSelectQuestionActionPerformed

    private void cmdCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdCloseAppActionPerformed

    private void cmdLoadQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoadQuestionActionPerformed
        String varSelect= jcbSelectQuestion.getSelectedItem().toString();
        if(varSelect!=""){
            clsQuestion varObj = clsControllerDomain.opGetInstance().opGetQuestionForName(varSelect);
            if (varObj!=null) {
                attQuestion.setVisible(true);
                attQuestion.opUpdateQuestion(varObj);
                attQuestion.opLoadUI();
            }else{
                JOptionPane.showMessageDialog(null, "Verifique la seleccion", "Advertecia", JOptionPane.WARNING_MESSAGE);
            } 
        }
    }//GEN-LAST:event_cmdLoadQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new uiSelectQuestion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCloseApp;
    private javax.swing.JButton cmdLoadQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcbSelectQuestion;
    private javax.swing.JPanel jpSelectQuestion;
    // End of variables declaration//GEN-END:variables
}
